### PR TITLE
Separate api module for the greetservice

### LINKED ISSUE #27: Decouple OSGi service and api to standalone bundles
I am not sure why the greeter api now is packaged with the base app, but any service should have it's own api bundle.
Please decouple the Greetservice, see:

https://github.com/Maurice-Betzel/base-starter-flow-karaf/tree/update-19.0.1

### PR DESCRIPTION
**Pull request by mstahv**
Closes #27

### CODE REVIEW

**Review by denis-anisimov — COMMENTED** [review]
I'm against these changes overall: it complicates a project a lot.
It has been already not a starter project since it's not possible to understand what parts can be reused by someone who wants to make a new Karaf poject and which are irrelevant.

If I want to make a simple Karaf project I have to remove too many things which are irrelevant for me. And what's worse : I have to understand what's relevant and what's not.

These changes complicates the project even more. 4 modules instead of 1 doesn't give me any chance to understand how to START making my own project.

This is not a starter anymore: it's a demo.
Starter should be something that I may use to start.
Demo should be extracted to a separate repo and can be used to demo features

**Comment by Maurice-Betzel** [comment]
That are some valid reasons not to extract the API.

**Comment by mstahv** [comment]
I consider this more of an example/demo already than a starter project. If people will start on this, they will also most likely want to delete the help-view as well.

I'll rename this project and later this week make a PR to refactor the the module names.I'll rename starter (aka project-base-karaf as module name) into main-ui. Fits well when this is made into an example instead of started and I think it will make the project structure easier to figure out as well evaluators.

**Comment by mstahv** [comment]
Project is now renamed, and other "branding to an example project" tasks started in #45

**Review by denis-anisimov — APPROVED** [review]
The project is broken at the moment since OSGi 7.0 SNAPSHOT is built against 8.0 Flow (this is a separate issue).
But otherwise it looks OK: the service API dependency is included to the feature definition and it should be possible to start the project as before via maven.

The project becomes a demo and I would like to avoid maintain the demo: it requires too much efforts: starter is relatively easy to maintain, demo is a totally different thing.

**Pull request merged**
